### ISSUE TITLE
An error occurred when parsing the Cookie header for Uri

### ISSUE THREAD

**Issue by oliverwhk** [AngleSharp/AngleSharp#431]
Hi there,

I'm trying to load a webpage with cookie add-on but encountered error:
- {"An error occurred when parsing the Cookie header for Uri."}
- Inner exception: {"Cookie format error."}

Here is my code:

``` cs
var SiteUrl = "http://www.paknsave.co.nz/";
var config = Configuration.Default.WithDefaultLoader().WithCookies();
_browsingContext = BrowsingContext.New(config);
var document = await _browsingContext.OpenAsync(Url.Create(SiteUrl));
```

Any idea why?

Thanks,
Oliver

**Comment by FlorianRappl** [comment]
Due to some reason the page is sending version 1 cookies. This is how the cookie looks:

``` plain
$Version=1; FGTServer=04E2E1A642B2BB49C6FE0115DE3976CB377263F3278BD6C8E2F8A24EE4DF7562F089BFAC5C0102
```

However, the following is expected:

``` plain
FGTServer=04E2E1A642B2BB49C6FE0115DE3976CB377263F3278BD6C8E2F8A24EE4DF7562F089BFAC5C0102; Version=1; Max-Age=3600
```

As an intermediate workaround you could roll out your own cookie provider:

``` cs
public class ImprovedMemoryCookieProvider : ICookieProvider
{
    private readonly CookieContainer _container;

    /// <summary>
    /// Creates a new cookie service for non-persistent cookies.
    /// </summary>
    public ImprovedMemoryCookieProvider()
    {
        _container = new CookieContainer();
    }

    /// <summary>
    /// Gets the associated cookie container.
    /// </summary>
    public CookieContainer Container
    {
        get { return _container; }
    }

    /// <summary>
    /// Gets the cookie value of the given address.
    /// </summary>
    /// <param name="origin">The origin of the cookie (Url).</param>
    /// <returns>The value of the cookie.</returns>
    public String GetCookie(String origin)
    {
        return _container.GetCookieHeader(new Uri(origin));
    }

    /// <summary>
    /// Sets the cookie value for the given address.
    /// </summary>
    /// <param name="origin">The origin of the cookie (Url).</param>
    /// <param name="value">The value of the cookie.</param>
    public void SetCookie(String origin, String value)
    {
        if (value.StartsWith("$Version", StringComparison.OrdinalIgnoreCase))
        {
            var index = value.IndexOf(';');

            if (index >= 0)
            {
                var main = value.Substring(index + 1);
                var version = value.Substring(1, index - 1);
                var separator = main.EndsWith(";") ? String.Empty : ";";
                value = main + separator + version;
            }
            else
            {
                value = value.Substring(1);
            }
        }

        _container.SetCookies(new Uri(origin), value);
    }
}
```

Use it as follows:

``` cs
var config = Configuration.Default.WithDefaultLoader().With(new ImprovedMemoryCookieProvider());
```

**Comment by FlorianRappl** [comment]
I dropped the `bug` as this is an RFC2965 cookie, which is not supported by the cookie container. As an improvement, I'll try to make it supported by AngleSharp.

**Comment by oliverwhk** [comment]
@FlorianRappl Wow, thanks for your prompt reply & update. Very much appreciated ;)

**Comment by FlorianRappl** [comment]
Actually, looking at this a second time - it is a bug. I was foolish to assume that setting a cookie (c) and then obtaining the cookie (c') from a cookie container is an operation that obeys c = c'. However, I was wrong as setting a cookie assumes `set-cookie` and getting a cookie assumes placing it in a `cookie` header. Unfortunately, these are two different strings, i.e., c != c'.

**Comment by FlorianRappl** [comment]
Fixed, see PR #433.

**Comment by oliverwhk** [comment]
@FlorianRappl hi there, I'm still getting same error for this page. Can you please take a look why?

http://www.thewarehouse.co.nz/p/windows-10-14-inch-notebook-grey/R2134888.html

Thanks heaps!
Oliver

**Comment by FlorianRappl** [comment]
The reason is simple: You are still on v0.9.9 (v0.10 was not released yet, so you will have to build directly from the sources in `devel`). Can you retest on v0.10?

**Comment by oliverwhk** [comment]
@FlorianRappl I have merged the #433 fix to Master branch locally and tested. Or is there other fix in devel branch that resolves the issue?

Btw, I have also tested version off devel branch and it's also giving me same error
![image](https://cloud.githubusercontent.com/assets/3687980/22285108/291a1e1a-e34f-11e6-9579-4d29643827a8.png)

**Comment by FlorianRappl** [comment]
Please try to make a MWE independent of the website to reproduce the exact issue (in the best case a `[Test]` would be ideal). Then we can sort it out more easily. Thanks!

(makes it easier to reproduce the issue and have fruitful discussion about it - also the definition of "fixed" would then improve)

**Comment by oliverwhk** [comment]
Sure, thanks for your help.

**Comment by georgiosd** [comment]
This same error happens when the cookie includes a command (and no quotes) in the date - 

`Set-Cookie: username=""; Domain=.foo.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/`
