### ISSUE TITLE
Wrong "The string did not match the expected pattern" exception

### ISSUE THREAD

**Issue by drungrin** [AngleSharp/AngleSharp#550]
The devel branch is raising this exeption when calling QuerySelector on an empty INodeList. It should return an empty list.

Where:

https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Dom/QueryExtensions.cs#L215-L223

Maybe there and variants should short-return an empty list (or whatever is returned on a not found case) on an empty nodelist

https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Dom/QueryExtensions.cs#L40-L45

**Comment by FlorianRappl** [comment]
You are right here, but the other side (returning the empty list in such cases) may also be wrong. Problem here is that a node is needed to transport the context, which gives access to the parser. Maybe we should use a default parser in such cases - but that could lead to inconsistencies.

I'll see what options come to my mind (I guess we'll need to transport the context explicitly then).

**Comment by drungrin** [comment]
I believe that on master it returned a empty list (not sure). 
You should not need the node to search on an empty node list, just return whatever a "NotFound" would return.

**Comment by FlorianRappl** [comment]
No, that is not the issue. Throwing a syntax exception is. The parser must still be invoked (like in the browser). Hence see my comment above.

**Comment by drungrin** [comment]
Sorry, I didn't got it. Why the parser should be invoked to query a selector over a empty node list? Should not be a optimization to return the "not found" (null on QuerySelector), since the result is known to be "not found"?

**Comment by FlorianRappl** [comment]
Yes, but in order to be *always* consistent the parser must also run *always*. In general, though the `NodeList` is not empty (as such not invoking the parser could be considered a micro optimization). 

Consider `myNodeList.QuerySelector("<invalidSyntax>")`. It should not just return an empty list - as throwing an error would then depend on the state of the `myNodeList` instance. If something is fishy with the syntax it should just throw an exception. BTW: The same is true (and was the motivation) for the `NodeList`.

As a conclusion I think that going for a special exception (invalid operation) for passing in empty `NodeList` may be the right thing to do. It would avoid being inconsistent and it would also avoid being confusing. Again, this part is user invoked (and will never be triggered from the `document` / standard `QuerySelector/All` methods.

**Comment by drungrin** [comment]
Got it about invoking the parser, it should throws on an invalid syntax, and it is needed to check the syntax, being consistent in that way, and I agree with that.

I don't agree about an invalid operation, it 'll break existing code (broke mine), and, for me, be inconsistent, unless if the query also throws InvalidOperation when no records found. Being consistent is the query returning the same as a "not found" query.

**Comment by FlorianRappl** [comment]
I don't see how your code can be broken. If so it was broken from the beginning (breaking means it worked and then it stopped working).

I am still dazzled about the "not found" query. What should that be?

Let's recap: We need to invoke the parser to identify wrong syntax. In order to identify a wrong syntax a `NodeList` needs to be supplied. If no `NodeList` is supplied we cannot check the syntax and thus have to throw an exception. The method therefore requires a non-empty `NodeList`.

I don't know how else to express it. You also cannot supply empty lists for some LINQ methods. Do you consider those breaking as well? No - it's the user not supplying arguments that meet the requirements.

**Comment by drungrin** [comment]
Considering `<html><head></head><body><p>Paragraph</p></body></html>`

and you do a `QuerySelectorAll("a")`. It should return the same over this document, and over an empty list (document.Head.ChildNodes). That is the "Not Found", sorry about not being clear about this.

If that was LINQ, you could do:

document.Head.ChildNodes.ToList().Where(n => n.NodeName == "a").Count()
document.Body.ChildNodes.ToList().Where(n => n.NodeName == "a").Count()

It would raise no error, and ends with 0.

First() raises an error, because you are selecting the first, and that becomes a constraint. Maybe we should have a QuerySelectorOrDefault().

Filtering doesn't raises a error, because an empty list, when filtered, 'll result an empty list, like the LINQ example above, and being consistent with LINQ, and not making inconsistent requirements :).

**Comment by FlorianRappl** [comment]
Ok, I think I need to be a little bit more specific here, otherwise I feel we are talking in different directions:

* The bug itself is that the call to the extension method itself is wired wrong. Hence even though we have a context we do not use it. This is wrong and results in an exception that should not be. It is, however, only available in `devel` (but I'm glad it got caught before it reaches production). This one is indeed breaking. No discussion here.
* Using the extension method directly (e.g., via `document.Head.ChildNodes.QuerySelector`) may still result in an exception, however, only if there is not a single child node and no context was given. Maybe the extension method should be hidden. Otherwise, there is no way to make it consistent. It needs at least one node to make the syntax evaluation. This one is needed due to reasons stated in this discussion.

So regarding your last reply: If you invoke it directly from `document.Head.ChildNodes` then this is somewhat anticipated (no context can be retrieved), even though a different exception should appear in my opinion. If you invoke it from `document.Head` then this is the bug that I labeled after you opened this issue.

**Comment by drungrin** [comment]
Considering `<html><head></head><body><p>Paragraph</p></body></html>`

I'm convinced about the bug itself, and your concerns about having to call the parser to validate and throw an exception on an invalid syntax.  It is correct, the bug labeled there happens if we invoke it from `document.Head`.

But while we discussed, I found that if you throw a invalid operation on QuerySelectorAll, it'll not be consistent. I believe it should behave like LINQ.

```
document.Body.ChildNodes.ToList().Where(n => n.NodeName == "p").Count(); // 1
document.Head.ChildNodes.ToList().Where(n => n.NodeName == "p").Count(); // 0

document.Body.QuerySelectorAll("p").Count(); // 1
document.Head.QuerySelectorAll("p").Count(); // 0
document.Body.QuerySelector("p"); // the IHtmlParagraphElement
document.Head.QuerySelector("p"); // InvalidOperationException
document.Body.QuerySelectorDefault("p"); // the IHtmlParagraphElement
document.Head.QuerySelectorDefault("p"); // default(IElement)
```

I also believe most of the users 'll get an exception using it, what 'll happen if you throw an InvalidOperationException, because everyone expect LINQ behavior.

Another question:

When comparing with LINQ, I don't know if the atual QuerySelector should behave like First() or like Single().

Should we need to have a QuerySelector that returns a single node? Wouldn't we just have a QuerySelector that returns a INodeList, and then use the standard LINQ methods (First, Single...)?

**Comment by FlorianRappl** [comment]
1. I think you misunderstood. It should *not* behave like LINQ. It should behave like the specification states.
2. Why should `document.Head.QuerySelector("p");` throw an exception? It is a legit selector + invoked from a context. That should always be fine.
3. There will never be a `xDefault` method.

It is neither `First` nor `Single`. It is more like `FirstOrDefault`, but since the input collection is a tree (i.e., not flat collection) it cannot be compared at all (unless you specify the walking algorithm). `Single` would imply looking at the whole tree, but `QuerySelector` stops after the first hit.

**Comment by FlorianRappl** [comment]
Fixed, see PR #551. Let's continue the discussion there and reach a conclusion / refine to find a third way as described in #551.

**Comment by renewfrl** [comment]
@FlorianRappl I still get this error when adding a new map. (2.0.4)

(for example: https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-100-mun.json)
